# Generated by Django 4.2 on 2023-05-18 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treads',
            name='main_treads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_tread', to='forum.maintreads'),
        ),
    ]
