# Generated by Django 4.2 on 2023-05-10 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230510_1036'),
        ('main', '0004_news_views'),
    ]

    operations = [
    ]
